on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  playwright-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: actions/checkout@v4
      - run: |
          nix-shell --run build-site-bin-nix
          #nix-shell --run run-site-bin-nix &
          #nix-shell --run playwright-run-ci
          nix build -L github:phanirithvij/nixpkgs/bump-pagefind-1725329421#pagefind -o result-pf
          nix build -L github:phanirithvij/nixpkgs/bump-pagefind-1725329421#pagefind -o result-pf --rebuild # just to be sure
          nix-store --export $(nix-store --query --requisites ./result-pf) > pagefind-1.1.1.nix-store
      - uses: actions/upload-artifact@v4
        with:
          name: pagefind-nix-store-${{ matrix.os }}
          path: |
            pagefind-1.1.1.nix-store
