on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  playwright-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
            substituters = https://nix-community.cachix.org https://cache.nixos.org
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: omnigres/tailscale-github-action@macos
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.74.1
      - run: |
          nix build -L github:phanirithvij/nixpkgs/patch-1#pagefind -o result-pf
          #nix build -L github:nixos/nixpkgs/refs/pull/344950/merge#pagefind -o result-pf --rebuild
          nix-store --export $(nix-store --query --requisites ./result-pf) > pagefind-1.1.1.nix-store
      - uses: actions/upload-artifact@v4
        with:
          name: pagefind-nix-store-${{ matrix.os }}
          path: |
            pagefind-1.1.1.nix-store
      - if: ${{ runner.os == 'Linux' }}
        run: |
          git clone https://github.com/nix-community/noogle
          cd noogle
          nix build .#ui
          cd ..
          sudo cp -r ./noogle/result/lib/node_modules/noogle/out out
          sudo chmod 777 -R out
      - if: ${{ runner.os == 'macOS' }}
        run: |
          mkdir out
          cd out
          echo "<html><body>hi</body></html>" > index.html
      - run: |
          ./result-pf/bin/pagefind -s out --serve --verbose &
          nix profile install nixpkgs#caddy
          caddy reverse-proxy --from :2080 --to :1414
