on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  playwright-test:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= nixpkgs-unfree.cachix.org-1:hqvoInulhbV4nJ9yJOEr+4wxhDV4xq2d1DK7S6Nj6rs=
            substituters = https://nix-community.cachix.org https://cache.nixos.org https://nixpkgs-unfree.cachix.org
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: omnigres/tailscale-github-action@macos
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: 1.74.1
      - run: |
          export NIXPKGS_ALLOW_UNFREE=1
          nix build -L github:nixos/nixpkgs/nixos-unstable#mongodb-7_0 --impure -o result-mdb
          nix-store --export $(nix-store --query --requisites ./result-mdb) > mongodb.nix-store
      - uses: actions/upload-artifact@v4
        with:
          name: mongodb-nix-store
          path: |
            mongodb.nix-store
